### ISSUE TITLE
Fix the swagger for the GET request to list all players 

### ISSUE THREAD

**Issue by davicunha31** [gameontext/gameon-player#63]
Hi Erin,

Just to remember to fix the swagger for the GET request to list all players to include the type that will be returned , so I can see the information (id) in response. 

Should be this guy coming back in the list: 
PlayerArgument {
_id (string): Unique player id ,
name (string): Player name ,
favoriteColor (string): Favorite color
}

Thanks,

**Comment by ebullient** [comment]
We're all set. Thanks for opening!
